//! Generated gateway bootstrap for sdkwork-modelkit.
//! Regenerated by pnpm gateway:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub fn assemble_application_router() -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_modelkit_http_auth::gateway_mount());
    ApplicationAssembly { router }
}
