const fs = require('fs');

const mappings = {
  "en/news.json": {
    "txt_1000": "Back to List",
    "txt_1001": "In this newly disclosed incident, attackers bypassed front-end detection rules to directly access core backend vulnerabilities. The impacted network scope is under evaluation, but unauthorized data access is possible. The severity has been raised due to its low exploit threshold and potential for privilege escalation.",
    "txt_1002": "Deep Vulnerability Analysis & Attack Tracing",
    "txt_1003": "According to CERT and security partners, the root cause is the application interface's lack of strict input validation for specific headers and user agents. This caused unexpected state overflows during serialization, bypassing all security verifications.",
    "txt_1004": "Sandbox PoC tests confirmed that sending a specially crafted HTTP payload to the defective API completely bypasses authentication, allowing arbitrary code execution or high-level system privileges.",
    "txt_1005": "Emergency Patches & Security Hardening",
    "txt_1006": "We urge all users to immediately patch the affected components to the latest secure version. Additionally, add WAF signature filtering rules to block abnormal packets.",
    "txt_1007": "To improve overall defense reliance, we recommend in the next cycle:",
    "txt_1008": "Refactor and audit all horizontal privilege escalation paths;",
    "txt_1009": "Enforce strict input validation mechanisms (whitelist-based);",
    "txt_1010": "Shift defense down to the micro-core application layer and enforce Zero Trust standard.",
    "txt_1011": "Latest Articles",
    "txt_1012": "Popular Articles",
    "txt_1014": "Seebug Latest Paper",
    "txt_1015": "Scan to read more",
    "txt_1016": "Search on WeChat",
    "txt_1017": "Security Thread Landscape"
  },
  "en/relay.json": {
    "txt_1018": "About this endpoint",
    "txt_1019": "Base API URL"
  },
  "en/repos.json": {
    "txt_1020": "Git Clone Address",
    "txt_1021": "Recommendation Reason",
    "txt_1022": "About this repository",
    "txt_1023": "Submit / Recommend Repository",
    "txt_1024": "Git Repository URL",
    "txt_1025": "Organization Name",
    "txt_1026": "Repository Name",
    "txt_1027": "Primary Language",
    "txt_1028": "Category",
    "txt_1029": "Short Description",
    "txt_1030": "Why recommend this repository?",
    "txt_1031": "Submitter Email (Optional)"
  },
  "en/skillhub.json": {
    "txt_1145": "Source Code"
  },
  "en/software.json": {
    "txt_1146": "One-click Install",
    "txt_1147": "Local Setup State",
    "txt_1148": "Installed Locally",
    "txt_1149": "Not Installed",
    "txt_1150": "Connection State",
    "txt_1151": "EDITOR'S PICK"
  },
  "en/workspace.json": {
    "txt_1153": "Permission Level:",
    "txt_1154": "Root System Admin",
    "txt_1155": "User Profile",
    "txt_1156": "System Settings",
    "txt_1157": "Order History",
    "txt_1158": "Shopping Cart",
    "txt_1159": "Lock Session",
    "txt_1167": "Component Tools",
    "txt_1168": "Loading...",
    "txt_1169": "No matching component found",
    "txt_1170": "Relay Nodes List",
    "txt_1171": "No available routing nodes",
    "txt_1172": "Local Key Config",
    "txt_1173": "Config Panel",
    "txt_1174": "Searching for components...",
    "txt_1175": "Api Key Management",
    "txt_1178": "One-Click Install",
    "txt_1179": "Installed",
    "txt_1181": "Active Node",
    "txt_1182": "Setup Wizard",
    "txt_1183": "Deploying terminal daemon to your workspace...",
    "txt_1184": "Rate",
    "txt_1185": "Architecture",
    "txt_1186": "Thread State",
    "txt_1187": "Bottom Port",
    "txt_1188": "Deploy Environment",
    "txt_1189": "Component is currently uninstalled due to missing local dependency runtime context. Please choose the suitable deployment mode.",
    "txt_1190": "CLI Command Line Tool",
    "txt_1191": "Based on Node.js lite kernel, deployed via npm. High efficiency and low memory footprint.",
    "txt_1192": "Executable command:",
    "txt_1193": "Configure Now &rarr;",
    "txt_1194": "Desktop GUI Application",
    "txt_1195": "Standalone visual app with a tray control panel and auto background startup.",
    "txt_1196": "App size:",
    "txt_1197": "Configure Now &rarr;",
    "txt_1198": "System Pre-checks",
    "txt_1199": "OS Compatibility",
    "txt_1200": "Node.js Toolkit",
    "txt_1201": "Local Port 3000 mapping",
    "txt_1202": "Launch Deployment",
    "txt_1204": "Key Name",
    "txt_1205": "API Key",
    "txt_1207": "Custom Endpoint (Base URL - Optional)",
    "txt_1209": "Cancel",
    "txt_1210": "Save",
    "txt_1211": "Install Mode",
    "txt_1212": "Please select the mode for",
    "txt_1213": "Select the installation mode suitable for your system architecture:",
    "txt_1214": "Command Line Tool",
    "txt_1215": "Headless daemon triggered from Terminal, excellent for devs.",
    "txt_1216": "GUI Application",
    "txt_1217": "Native desktop container supporting visual dashboard and network tunnels.",
    "txt_1218": "Cancel",
    "txt_1221": "Name",
    "txt_1222": "OpenAI URL",
    "txt_1224": "Anthropic URL",
    "txt_1226": "Model ID",
    "txt_1227": "API Key",
    "txt_1229": "Cancel",
    "txt_1230": "Save",
    "txt_1231": "Cancel VIP Subscription",
    "txt_1232": "Are you sure you want to cancel the VIP flagship subscription? You will lose access to premium models and routing lines.",
    "txt_1233": "Keep Subscription",
    "txt_1234": "Confirm Cancel",
    "txt_1237": "Current Context",
    "txt_1239": "Access Params",
    "txt_1240": "Custom Config",
    "txt_1241": "Custom Config",
    "txt_1244": "Manage & Test",
    "txt_1246": "API Format",
    "txt_1247": "Anthropic Messages (Native)",
    "txt_1248": "OpenAI Format (Proxy)",
    "txt_1249": "Select the input format of the provider API",
    "txt_1250": "Auth Header",
    "txt_1251": "ANTHROPIC_AUTH_TOKEN (Default)",
    "txt_1252": "Select the Auth env variable name",
    "txt_1253": "Main Model",
    "txt_1254": "Reasoning Model",
    "txt_1255": "Default Haiku Model",
    "txt_1256": "Default Sonnet Model",
    "txt_1257": "Default Opus Model",
    "txt_1258": "Optional: Specific Claude models to default to",
    "txt_1259": "Model Name",
    "txt_1260": "Specific Model, updates in config.toml",
    "txt_1262": "Smart Gateway Inbound Interceptor",
    "txt_1263": "Inbound deep eco-link detected, executing auto-mount strategy",
    "txt_1264": "Eco-Shared Payload",
    "txt_1265": "Target Name:",
    "txt_1266": "Endpoint BaseUrl:",
    "txt_1268": "Payload Desc:",
    "txt_1270": "Credentials:",
    "txt_1271": "Synced and Mounted to local group",
    "txt_1272": "Import & Register Key",
    "txt_1273": "3. Select Tool App Profile Strategy",
    "txt_1274": "Dispatch Strategy",
    "txt_1275": "Compile Passed: Mounted to Virtual Sandbox",
    "txt_1277": "End-to-End Encrypted & Compliant",
    "txt_1279": "Packet Deep Scan",
    "txt_1280": "Close",
    "txt_1281": "Session Duration:",
    "txt_1282": "Datagram Unique Hash:",
    "txt_1283": "Provider:",
    "txt_1285": "Model ID:",
    "txt_1287": "Execution Latency:",
    "txt_1288": "Node IP:",
    "txt_1289": "Request Payload",
    "txt_1290": "Proxy Response Data",
    "txt_1291": "NIC Decryption Audit",
    "txt_1293": "Sniff",
    "txt_1294": "Mock Payload",
    "txt_1295": "Search path, tools, models...",
    "txt_1296": "Clear Logs",
    "txt_1298": "Analysis Timeframe",
    "txt_1300": "Export Report",
    "txt_1301": "All Proxy Gateway Nodes",
    "txt_1302": "QPS:",
    "txt_1303": "Model Usage Breakdown",
    "txt_1304": "Distribution share across runtimes among various models",
    "txt_1307": "Today",
    "txt_1308": "Summary",
    "txt_1309": "Yesterday",
    "txt_1310": "This Month",
    "txt_1311": "Estimated Cost",
    "txt_1312": "Request Volume",
    "txt_1313": "Token Consumption",
    "txt_1314": "Gateway Performance",
    "txt_1318": "Reqs",
    "txt_1319": "Count:",
    "txt_1321": "Tokens:",
    "txt_1322": "Avg Latency:",
    "txt_1325": "Local Storage & Bundle Resources",
    "txt_1326": "Route Bundles and Snapshot Cache",
    "txt_1327": "Local storage allocated:",
    "txt_1328": "Clear Cache",
    "txt_1330": "Developer Center",
    "txt_1331": "VIP Flagship",
    "txt_1332": "Runtime Node Identity",
    "txt_1333": "Developer Hash / ID",
    "txt_1335": "You are currently running in debug mode, maintaining NIC traversal, Daemon payload capabilities and hot-reloading context privileges.",
    "txt_1336": "Independent API access management",
    "txt_1340": "Cashier - Verify Subscriptions",
    "txt_1341": "Product Name:",
    "txt_1342": "Billing Cycle:",
    "txt_1344": "Total Payable:",
    "txt_1345": "Secure Payment Option",
    "txt_1346": "Alipay",
    "txt_1347": "WeChat Pay",
    "txt_1348": "UnionPay / CC",
    "txt_1349": "2W Secure Encryption Channel",
    "txt_1350": "Please use an e-wallet to scan to complete payment",
    "txt_1351": "This is sandbox integration mock. No real charges occur.",
    "txt_1352": "Card Number",
    "txt_1353": "Expiry Date",
    "txt_1354": "CVV/CVC Code",
    "txt_1355": "🛡️ The financial sandbox has prepared a virtual bank shield for auto-deduction. Simply click 'Mock Payment Complete' below to inject the credential verification.",
    "txt_1356": "Sending payment authorization...",
    "txt_1357": "[INFO] Writing immutable key group and allocations...",
    "txt_1358": "VIP Subscription Activated!",
    "txt_1359": "Thank you for supporting ModelKit! Your global physical route QPS limits are maximized and high-tier models are securely loaded.",
    "txt_1360": "Hot-reloaded VIP authentication tokens. Fully downgrade-free.",
    "txt_1361": "Start enjoying privileges",
    "txt_1362": "Financial Grade AES-256",
    "txt_1363": "Cancel Order",
    "txt_1364": "Mock Payment Complete",
    "txt_1365": "VIP Activated",
    "txt_1366": "Upgrade to ModelKit VIP Flagship",
    "txt_1367": "Extreme low latency, massive concurrency dedicated line. Free from frequent auth limits.",
    "txt_1370": "Save 30%",
    "txt_1371": "You have currently activated",
    "txt_1373": "VIP Member",
    "txt_1374": "Core links successfully switched to high-bandwidth peer-to-peer VIP endpoints.",
    "txt_1375": "Go to User Center",
    "txt_1376": "Cancel Sub",
    "txt_1378": "Included Privileges:",
    "txt_1380": "Millisecond Connections",
    "txt_1381": "Backbone parity nodes, reducing latency by over 35%",
    "txt_1382": "Financial-grade Security",
    "txt_1383": "Two-way high-density encrypted channels per datagram",
    "txt_1384": "No Overhead Margin",
    "txt_1385": "Multiplexed compression hits repeating prompts, cutting costs",
    "txt_1386": "Multi-group dev verification",
    "txt_1387": "Multi-node hot swap DR disaster recovery built-in",
    "txt_1388": "Enterprise Node SLA",
    "txt_1389": "Capability Matrix",
    "txt_1390": "Standard Tier",
    "txt_1391": "Pro Developer VIP",
    "txt_1392": "Enterprise BareMetal",
    "txt_1393": "Max Virtual Physical Nodes",
    "txt_1394": "1 Gateway Router",
    "txt_1395": "Infinite Physical Load Tunnel",
    "txt_1396": "Authorized per hardware",
    "txt_1397": "Mass Model Coverage",
    "txt_1398": "Classic GPT-4o-mini & 5 models",
    "txt_1399": "Total Elite Matrix (o3, Opus)",
    "txt_1400": "Including Local LoRA mounts",
    "txt_1401": "SLA Uptime",
    "txt_1402": "Public Default (Fair-use)",
    "txt_1403": "VIP APAC & EU Backbone Auto",
    "txt_1404": "Dedicated Instance 99.99%",
    "txt_1405": "Daily API Limits",
    "txt_1406": "300 Calls / 1GB IO",
    "txt_1407": "Completely Infinite",
    "txt_1408": "Unmetered Usage",
    "txt_1409": "Fault Resilience Response",
    "txt_1410": "Community Queue",
    "txt_1411": "2hr Expert Ticket",
    "txt_1412": "15m VIP Dedicated Direct",
    "txt_1033": "Since a local Node.js Daemon Co-process is hooked into your environment, the client supports real-time packet checking. If timeout occurs, please ensure your parameters and API keys are not expired."
  }
};

for (const p of Object.keys(mappings)) {
  const file = 'src/locales/' + p;
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  const map = mappings[p];
  for (const k of Object.keys(map)) {
    data[k] = map[k];
  }
  fs.writeFileSync(file, JSON.stringify(data, null, 2));
}

console.log('Fixed multiple json files.');
