const fs = require('fs');

const shopEn = {
  "shopping_cart": "Shopping Cart",
  "your_cart_is_empty": "Your cart is empty",
  "total": "Total",
  "checkout_now": "Checkout Now",
  "category_tree": "Category Tree",
  "all_assets": "All Assets",
  "compute_network": "Compute & Network",
  "all_compute_net": "All Compute & Net",
  "api_credits": "API Credits",
  "secure_gateways": "Secure Gateways",
  "hardware_terminals": "Hardware Terminals",
  "all_hardware": "All Hardware",
  "mcp_core_box": "MCP Core-Box",
  "diy_boards_used": "DIY Boards & Used",
  "apparel_gear": "Apparel & Gear",
  "all_merchandise": "All Merchandise",
  "apparel_hoodie": "Apparel Hoodie",
  "keyboards_keycaps": "Keyboards & Keycaps",
  "my_orders_assets": "My Orders & Assets",
  "history_of_all_digital_keys_compute_credits_and_ph": "History of all digital keys, compute credits and physical items.",
  "no_orders_or_assets_found": "No orders or assets found.",
  "new_arrivals": "New Arrivals",
  "hottest": "Hottest",
  "recommended": "Recommended",
  "txt_1032": "Remove",
  "txt_1033": "Order No: ",
  "txt_1034": "Transaction Successful",
  "txt_1036": "Your Exclusive Digital Key / API Key",
  "txt_1037": "Physical item will be shipped to the address below",
  "txt_1042": "9k+ people want this",
  "txt_1043": "Pickup",
  "txt_1044": "Apply for Merchant",
  "txt_1045": "Quick Publish",
  "txt_1046": "Statement: The ",
  "txt_1047": "virtual items (compute, credit packs, keys)",
  "txt_1048": " will instantly generate a decryptable voucher code upon authorization for your server authentication.",
  "txt_1049": "Physical merchandise and node microcomputers",
  "txt_1050": " come with full logistics insurance and after-sales maintenance guarantee.",
  "txt_1054": "Search in Geek Assets...",
  "txt_1056": "Apply for Merchant",
  "txt_1057": "Become a Geek Asset Store merchant and freely publish your compute resources, API services, unused physical terminals, or customized peripheral.",
  "txt_1058": "Merchant / Team Name",
  "txt_1059": "Business Category",
  "txt_1060": "Compute Resources & API Services",
  "txt_1061": "Used & Hardware Terminals",
  "txt_1062": "Custom Dev Boards & Peripherals",
  "txt_1063": "Credentials (Optional)",
  "txt_1064": "Cancel",
  "txt_1065": "Submit Application (Demo)",
  "txt_1066": "e.g., Hacker Studio",
  "txt_1067": "GitHub Link or Personal Website",
  "txt_1069": "Quick Publish Product",
  "txt_1070": "Product Name*",
  "txt_1072": "Price (USDT/￥)*",
  "txt_1074": "Product Category",
  "txt_1075": "General Category",
  "txt_1076": "API Credits & Compute",
  "txt_1077": "Hardcore Physical Terminals",
  "txt_1078": "Secure Proxy Encryption",
  "txt_1079": "Product Icon (Emoji)",
  "txt_1081": "Short Description*",
  "txt_1083": "Voucher Link / External Purchase Link (Optional)",
  "txt_1084": "If filled, clicking purchase will redirect user to this external link.",
  "txt_1085": "Detailed Features (One per line)",
  "txt_1087": "Cancel",
  "txt_1088": "Confirm Publish",
  "txt_1089": "Product Checklist Total",
  "txt_1090": "Actual Total Amount: ",
  "txt_1091": "Physical Delivery Address (SF Express)",
  "txt_1092": "Consignee: ",
  "txt_1094": "Mobile Number: ",
  "txt_1096": "Detailed Address: ",
  "txt_1098": "Select Secure Payment Method",
  "txt_1099": "Alipay",
  "txt_1100": "WeChat Pay",
  "txt_1101": "UnionPay / Credit Card",
  "txt_1102": "Cancel",
  "txt_1103": "Confirm Order & Pay",
  "txt_1104": "Payment Carrier: ",
  "txt_1106": "Total Payable: ",
  "txt_1107": "Two-Way Secure Handshake",
  "txt_1108": "Please use an e-wallet to scan the QR code to process",
  "txt_1109": "This page is strictly for sandbox integration testing, no real charges will occur &nbsp;|&nbsp; Remaining Time",
  "txt_1110": "Mock Card Number",
  "txt_1111": "🛡️ The financial sandbox has prepared a virtual bank shield for auto-deduction. Simply click 'Mock Payment Complete' below to inject the credential verification.",
  "txt_1112": "Cancel",
  "txt_1113": "Mock Payment Complete",
  "txt_1114": "Sending payment and issuance packets to the transit router...",
  "txt_1115": "[SYS] Intercepting relay info, generating voucher codes and assigning orders...",
  "txt_1116": "Transaction securely delivered!",
  "txt_1117": "Your order has been marked as successfully delivered. You can",
  "txt_1118": "「Order History」",
  "txt_1119": " at any time to review, one-click copy your virtual voucher code or sync SF Express logistics track.",
  "txt_1120": "View My Order Voucher",
  "txt_1121": "Close Window",
  "txt_1123": "Back to Product List",
  "txt_1126": "Specification Options",
  "txt_1127": "Go to {merchant} to Buy",
  "txt_1128": "Add to Cart",
  "txt_1129": "Buy Now",
  "txt_1130": "100% Authentic",
  "txt_1131": "Guaranteed Sec. Trans.",
  "txt_1132": "Worry-Free Aftersales",
  "txt_1133": "Detailed Product Breakdown",
  "txt_1134": "Core Architectural Advantages",
  "txt_1135": "Geek Q&A Log",
  "txt_1136": "No geeks have thrown technical challenges yet",
  "txt_1137": "Launch the first interrogation, the seller will respond at full speed",
  "txt_1138": "Q",
  "txt_1139": "A",
  "txt_1141": "The owner is frantically typing the reply...",
  "txt_1142": "Verify Departure",
  "txt_1143": "Technical Resume & Params",
  "txt_1144": "Seek proof from buyers, enter your hardcore doubt..."
};

const file = 'src/locales/en/shop.json';
const data = JSON.parse(fs.readFileSync(file, 'utf8'));
for (const k of Object.keys(shopEn)) {
  data[k] = shopEn[k];
}
fs.writeFileSync(file, JSON.stringify(data, null, 2));
console.log('Fixed shop.json');
