export const VIP_PLANS = [
  {
    id: "basic",
    name: "Developer Basic",
    nameZh: "开发者基础版",
    description: "Ideal for solo developers for model invocation and routing performance testing.",
    descriptionZh: "适合个人独立开发者进行模型调用与路由性能测试",
    monthlyPrice: 29,
    yearlyPrice: 24,
    popular: false,
    features: [
      "Support for mainstream models (5+ core templates)",
      "Daily API rate limit of 1,500 gateway communications",
      "Standard response rate, concurrency limited to 5 QPS",
      "Basic data analysis & 7-day statistics",
      "GitHub community standard support channel",
    ],
    featuresZh: [
      "支持主流模型（5+ 种核心预设模型）",
      "接口单日限流 1,500 次网关通信",
      "标准响应速率，并发限制 5 QPS",
      "基础数据分析 & 近 7 日数据统计",
      "GitHub 社群标准支持通道",
    ],
    notIncluded: [
      "Excludes advanced inference model access (e.g., OpenAI o3/Claude Sonnet)",
      "Does not support VIP high-speed secure proxy channels",
      "No 1-on-1 technical advisor architecture support",
    ],
    notIncludedZh: [
      "不含高阶推理模型授权 (如 OpenAI o3/Claude Sonnet 精调等)",
      "不支持 VIP 高速多路安全代理通道",
      "无 1 对 1 技术顾问架构支持",
    ],
    tag: "Starter Choice",
    tagZh: "入门首选",
  },
  {
    id: "pro",
    name: "Flagship Developer Pro",
    nameZh: "旗舰开发者专业版",
    description: "Enjoy 10k concurrency, unbind full model matrix limits, and accelerate smart routing.",
    descriptionZh: "尊享万级并发，全模型矩阵解除调用上限，加速智能分流",
    monthlyPrice: 99,
    yearlyPrice: 79,
    popular: true,
    features: [
      "Full model matrix (30+ mainstream/private models & hot-pluggable)",
      "Multi-node proxy network with no hard cap (Infinite Proxy physical tunnels)",
      "High concurrency links (Ultra-low latency QPS up to 100)",
      "Full coverage of advanced inference & CoT models (o3-mini, Gemini Pro, etc.)",
      "Smart edge-side offloading, cache hit drops cost by 40%+",
      "Long-term data stats, performance dashboards, and D3 diagnostic maps",
      "VIP pro engineer 1-on-1 real-time config integration service",
    ],
    featuresZh: [
      "全模型矩阵（30+ 款主流/私有模型及自定义热插拔）",
      "无硬性上限的多节点代理网络（无限 Proxy 物理隧道）",
      "尊享万次并发高并发链路（极智延迟 QPS 高达 100）",
      "高阶推理及思维链模型全面覆盖 (o3-mini, Gemini Pro 等)",
      "智能端侧低碳分流，缓存命中扣费降低 40%+",
      "长周期数据统计、性能监控看板与 D3 深度诊断导图",
      "VIP 专业工程师 1对1 实时配置对接服务",
    ],
    tag: "Highly Recommended",
    tagZh: "强烈推荐",
  },
  {
    id: "enterprise",
    name: "Private Enterprise Team",
    nameZh: "私有化团队企业版",
    description: "Tailored multi-user channels for enterprise architecture and highly reliable deployments.",
    descriptionZh: "为企业团队架构及生产高可靠级部署提供定制化多用户通道",
    monthlyPrice: 299,
    yearlyPrice: 249,
    popular: false,
    features: [
      "Includes all Pro high-tier privileges",
      "Private network On-Premises Hub cluster direct mapping",
      "Multi-tenant sub-account auth control, independent quota allocation",
      "Fully secured precision communication firewall & two-way PGP encryption locks",
      "Physical dedicated server gateway fidelity, highly robust against anomalies",
      "Guaranteed 99.99% communication uptime (SLA official commitment)",
      "Custom dedicated integration gateway (private custom middleware assembly)",
    ],
    featuresZh: [
      "包含专业版全部高阶特权",
      "私有网络免穿透直接映射 (On-Premises Hub 集群接入)",
      "多租户子账户授权控制，独立配额统计分配",
      "全面保障的高精通信防火墙机制与安全双向 PGP 加密锁",
      "物理级专属服务器网关保真，高阻抗抵抗异常抖动",
      "保证 99.99% 通讯正常率（SLA 正式服务水平协定承诺）",
      "定制专属对接网关（非公开自定义中间件装配）",
    ],
    tag: "Team Exclusive",
    tagZh: "团队专享",
  },
];
